version: '3'

services:

  postgres:
    build: ./compose/postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/backups:/app/data
    env_file: .env

  redis:
    build: ./compose/redis
    ports:
      - "0.0.0.0:6379:6379"
    env_file: .env

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    command: /usr/local/bin/supervisord -c /app/bin/supervisord.conf --nodaemon
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./data/private:/app/private
      - ./data/public:/app/public

  nginx:
    build: ./compose/nginx
    depends_on:
      - app
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./data/public:/app/public
      - ./data/nginx/ssl:/etc/nginx/ssl
