[tool.black]
line-length = 100
target-version = ['py311']
extend-exclude = '(frontend|public|scripts/private)'

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["F", "E", "W", "I", "UP", "S", "B", "T20", "RUF"]
ignore = ["E501", "B904", "B007", "S308", "S113", "S314"]

[tool.ruff.isort]
known-first-party = ["bmds_server"]
known-third-party = ["bmds"]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101", "S106"]
"scripts/*.py" = ["T201"]
"**/management/**.py" = ["T201"]
"**/migrations/**.py" = ["T201"]
