# Generated by Django 4.2.8 on 2023-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_reversions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="analysis",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysis",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="analyses", to="analysis.collection"
            ),
        ),
    ]
