version: '3'

services:

  postgres:
    build: ./compose/postgres

  redis:
    build: ./compose/redis
    ports:
      - "0.0.0.0:6379:6379"

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile

  nginx:
    build: ./compose/nginx
