version: '3'

services:

    postgres:
        restart: always
        image: bmds-server_postgres
        env_file: .env
        volumes:
            - ./data/postgres/data:/var/lib/postgresql/data
            - ./data/postgres/backups:/app/data/backups

    redis:
        restart: always
        image: bmds-server_redis
        env_file: .env

    sync:
        restart: always
        image: bmds-server_app
        command:
        - /bin/bash
        - -exc
        - |
          set +xe
          /app/bin/wait-for.sh redis:6379 -t 30 -q
          /app/bin/wait-for.sh postgres:5432 -t 30 -q
          /app/bin/sync.sh
        depends_on:
            - postgres
            - redis
        env_file: .env
        volumes:
        - ./data/private:/app/private
        - ./data/public:/app/public

    web:
        restart: always
        image: bmds-server_app
        command:
        - /bin/bash
        - -exc
        - |
          set +xe
          /app/bin/wait-for.sh redis:6379 -t 30 -q
          /app/bin/wait-for.sh postgres:5432 -t 30 -q
          /app/bin/web.sh
        depends_on:
            - postgres
            - redis
        env_file: .env
        volumes:
            - ./data/private:/app/private
            - ./data/public:/app/public

    workers:
        restart: always
        image: bmds-server_app
        command:
        - /bin/bash
        - -exc
        - |
          set +xe
          /app/bin/wait-for.sh redis:6379 -t 30 -q
          /app/bin/wait-for.sh postgres:5432 -t 30 -q
          /app/bin/workers.sh
        depends_on:
            - postgres
            - redis
        env_file: .env
        volumes:
            - ./data/private:/app/private
            - ./data/public:/app/public
        healthcheck:
            test: ["celery", "--app=bmds_server.main.celery", "inspect", "ping", "-d", "celery@$$HOSTNAME", "--json"]
            interval: 60s
            timeout: 15s
            retries: 3
            start_period: 60s

    cron:
        restart: always
        image: bmds-server_app
        command:
        - /bin/bash
        - -exc
        - |
          set +xe
          /app/bin/wait-for.sh redis:6379 -t 30 -q
          /app/bin/wait-for.sh postgres:5432 -t 30 -q
          /app/bin/cron.sh
        depends_on:
            - redis
        env_file: .env

    nginx:
        image: bmds-server_nginx
        command: sh -c "/wait-for.sh web:5000 -t 30 -q && nginx -g \"daemon off;\""
        depends_on:
            - web
        ports:
            - "0.0.0.0:9000:9000"
        volumes:
            - ./data/public:/app/public
            - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
