# Generated by Django 2.2.11 on 2020-03-21 00:24

from django.db import migrations, models

import bmds_server.jobrunner.utils


class Migration(migrations.Migration):

    dependencies = [
        ("jobrunner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="password",
            field=models.CharField(
                default=bmds_server.jobrunner.utils.random_string, editable=False, max_length=12
            ),
        ),
        migrations.AddField(
            model_name="job", name="preferences", field=models.TextField(blank=True),
        ),
    ]
