# Generated by Django 3.1.4 on 2021-01-12 22:55

from django.db import migrations, models

import bmds_server.jobrunner.models


class Migration(migrations.Migration):

    dependencies = [
        ("jobrunner", "0002_ui_fields"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="preferences",),
        migrations.AddField(
            model_name="job",
            name="deletion_date",
            field=models.DateTimeField(
                blank=True, default=bmds_server.jobrunner.models.get_deletion_date, null=True
            ),
        ),
    ]
