site_name: BMDS Server Documentation
repo_url: https://github.com/shapiromatron/bmds-server
repo_name: shapiromatron/bmds-server
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue grey
    accent: brown
  features:
    - navigation.instant
    - navigation.tracking
nav:
  - index.md
  - development.md
  - deployment.md
  - desktop.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
        generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
