[tool.briefcase]
project_name = "BMDS Desktop"
bundle = "com.epa"
version = "0.0.1"
url = "https://bmdsonline.epa.gov"
license = "MIT license"
author = 'Andy Shapiro'
author_email = "shapiro.andy@epa.gov"

[tool.briefcase.app.bmdsdesktop]
formal_name = "BMDS Desktop"
description = "BMDS Online Desktop"
icon = "src/bmdsdesktop/resources/bmdsdesktop"
sources = ['src/bmdsdesktop']
requires = [
    'django'
]


[tool.briefcase.app.bmdsdesktop.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.bmdsdesktop.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.bmdsdesktop.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.bmdsdesktop.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.bmdsdesktop.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.bmdsdesktop.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.bmdsdesktop.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.bmdsdesktop.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
