name: ci-checks

on: [push]

jobs:
  # backend:
  #   name: backend
  #   runs-on: ubuntu-18.04

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v1
  #     with:
  #       python-version: '3.6'
  #       architecture: 'x64'
  #   - name: install
  #     run: |
  #       pip install -r requirements/ci.txt
  #   - name: lint
  #     run: |
  #       make lint-py
  #   - name: test
  #     run: |
  #       make test

  # frontend:
  #   name: frontend
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #   - name: install
  #     run: |
  #       yarn --cwd ./frontend install
  #   - name: lint
  #     run: |
  #       make lint-js

  docker:
    name: docker
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: install
      run: |
        yarn --cwd ./frontend install
        pip install -r requirements/ci.txt
    - name: build artifacts
      run: |
        make build
        wget -q https://files.pythonhosted.org/packages/46/bd/3ea83889e2f88ffcb9959435058994f35ce11adba3424f54b58a4d204336/bmds-0.11.0-py2.py3-none-any.whl -O ./vendor/bmds-1.0.0-py3-none-any.whl
        touch vendor ./vendor/libDRBMD.so
        touch vendor ./vendor/libnlopt.so
    - name: build docker container
      run: docker build . --file ./compose/app/Dockerfile
